# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_age', models.IntegerField(default=0)),
                ('rater_gender', models.CharField(max_length=1)),
                ('rater_job', models.CharField(max_length=20)),
                ('rater_zip', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('movie_id', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('time_stamp', models.IntegerField(default=0)),
            ],
        ),
    ]
